sudo: required

services:
  - docker

script:
  - docker info
  - docker version
  - docker-runc --version
  - docker-containerd --version
  - docker run -it --rm -u node node:alpine touch /root/hoge
