version: '2'
services:
  ruby: &ruby
    build:
      context: .
      args:
        HOST_UID: $HOST_UID
    depends_on:
      - postgres
    volumes:
      - ./rails:/app:cached
      - ./docker:/docker:cached
      - vendor:/vendor
      - home:/home/app
    env_file: .env
  ruby-2-3:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_IMAGE: ruby:2.3.4
        HOST_UID: $HOST_UID
  ruby-2-2:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_IMAGE: ruby:2.2.7
        HOST_UID: $HOST_UID
  ruby-trunk:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_IMAGE: mtsmfm/ruby-trunk
        HOST_UID: $HOST_UID
  postgres:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD:
volumes:
  home:
  vendor:
