version: '2'
services:
  ruby: &ruby
    build:
      context: .
    depends_on:
      - postgres
      - redis
      - memcached
    volumes:
      - ./rails:/app:cached
      - ./docker:/docker:cached
      - vendor:/vendor
      - home:/home/app
    environment:
      PGHOST: postgres
  ruby-2-3:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_IMAGE: ruby:2.3.4
  ruby-2-2:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_IMAGE: ruby:2.2.7
  ruby-trunk:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_IMAGE: mtsmfm/ruby-trunk
  postgres:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD:
  redis:
    image: redis:alpine
  memcached:
    image: memcached:alpine
volumes:
  home:
  vendor:
