version: '2'
services:
  ruby:
    image: mtsmfm/rails-dev-box
    working_dir: /app
    environment:
      BUNDLE_PATH: /tmp/vendor/bundle
    depends_on:
      - postgres
    volumes:
      - .:/app
      - bundle:/tmp/vendor/bundle
  postgres:
    image: postgres:9.4
volumes:
  bundle:
