version: '2'
services:
  ruby:
    image: mtsmfm/rails-dev-box
    working_dir: /app
    environment:
      BUNDLE_PATH: /app/vendor/bundle
    depends_on:
      - postgres
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      - home:/home/app
  postgres:
    image: postgres:9.4
volumes:
  home:
  bundle:
