version: '2'
services:
  ruby:
    build: .
    depends_on:
      - postgres
    volumes:
      - rails-rails-sync:/app
      - bundle:/app/vendor/bundle
      - home:/home/app
  postgres:
    image: postgres:9.4-alpine
volumes:
  home:
  bundle:
  rails-rails-sync:
    external: true
