version: "2"
services:
  ruby: &ruby
    build:
      context: .
      args:
        RUBY_IMAGE: ruby:2.5.1
    depends_on:
      - postgres
      - redis
      - memcached
    volumes:
      - ./rails:/app:cached
      - ./docker:/docker:cached
      - vendor-ruby:/vendor
      - home:/home/app
    environment:
      PGHOST: postgres
  ruby-2-5:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_IMAGE: ruby:2.5.1
    volumes:
      - ./rails:/app:cached
      - ./docker:/docker:cached
      - vendor-ruby-2-5:/vendor
      - home:/home/app
  ruby-2-4:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_IMAGE: ruby:2.4.4
    volumes:
      - ./rails:/app:cached
      - ./docker:/docker:cached
      - vendor-ruby-2-4:/vendor
      - home:/home/app
  ruby-trunk:
    <<: *ruby
    build:
      context: .
      args:
        RUBY_IMAGE: mtsmfm/ruby-trunk
    volumes:
      - ./rails:/app:cached
      - ./docker:/docker:cached
      - vendor-ruby-trunk:/vendor
      - home:/home/app
  postgres:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_USER: app
      ? POSTGRES_PASSWORD
  redis:
    image: redis:alpine
  memcached:
    image: memcached:alpine
volumes:
  ? home
  ? vendor-ruby
  ? vendor-ruby-2-5
  ? vendor-ruby-2-4
  ? vendor-ruby-trunk
