#!/usr/bin/env bash

set -ex

curl -sL https://github.com/mtsmfm/docker-rails-dev-box/raw/master/docker-compose.yml > docker-compose.yml
mkdir -p .git/info
touch .git/info/exclude
if ! grep -xq '/docker-compose.yml' .git/info/exclude > /dev/null; then
  echo '/docker-compose.yml' >> .git/info/exclude
fi

docker-compose down
docker-compose up -d && sleep 15
docker-compose exec ruby bundle install
docker-compose exec postgres psql -c "create database activerecord_unittest;" -U postgres
docker-compose exec postgres psql -c "create database activerecord_unittest2;" -U postgres

set +x

echo 'Setup finished!'
echo 'Now you can attach the ruby container via `docker-compose exec ruby bash`'
echo 'Enjoy development rails core!'
