#!/usr/bin/env bash

set -ex

download () {
  curl -sL https://github.com/mtsmfm/docker-rails-dev-box/raw/master/$1 > $1
}

write_line () {
  touch $1
  if ! grep -xq "$2" $1; then
    echo "$2" >> $1
  fi
}

mkdir -p .git/info

download docker-compose.yml
write_line .git/info/exclude '/docker-compose.yml'

mkdir -p docker/bin
download docker/bin/ruby
download docker/bin/rubocop
write_line .git/info/exclude '/docker'

docker-compose down
docker-compose up -d && sleep 15
docker-compose exec ruby bundle install
docker-compose exec postgres psql -c "create database activerecord_unittest;" -U postgres
docker-compose exec postgres psql -c "create database activerecord_unittest2;" -U postgres

set +x

echo 'Setup finished!'
echo 'Now you can attach the ruby container via `docker-compose exec ruby bash`'
echo 'Enjoy development rails core!'
