#!/usr/bin/env bash

set -ex

if -z "$BRANCH"; then
  BRANCH=master
fi

download () {
  curl -sL https://github.com/mtsmfm/docker-rails-dev-box/raw/$BRANCH/$1 > $1
}

write_line () {
  touch $1
  if ! grep -xq "$2" $1; then
    echo "$2" >> $1
  fi
}

mkdir -p .git/info

download docker-compose.yml
download docker-sync.yml
download Dockerfile
download activerecord/test/config.yml

write_line .git/info/exclude '/docker-compose.yml'
write_line .git/info/exclude '/docker-sync.yml'
write_line .git/info/exclude '/Dockerfile'

docker volume create rails-rails-sync
container=$(docker container create -v rails-rails-sync:/app_sync busybox)
docker cp . $container:/app_sync
docker container rm $container

docker-sync start

docker-compose down
docker-compose build
docker-compose up -d && sleep 15
docker-compose exec ruby bundle install
docker-compose exec postgres psql -c "create database activerecord_unittest;" -U postgres
docker-compose exec postgres psql -c "create database activerecord_unittest2;" -U postgres

set +x

echo 'Setup finished!'
echo 'Now you can attach the ruby container via `docker-compose exec ruby bash`'
echo 'Enjoy development rails core!'
