#!/usr/bin/env ruby

system 'bundle check || bundle install'

spawn 'redir --lport=6379 --cport=6379 --caddr=redis'
spawn 'redir --lport=11211 --cport=11211 --caddr=memcached'

require 'bundler/setup'
require 'active_record'

begin
  ActiveRecord::Base.establish_connection('adapter' => 'postgresql')

  %w(activerecord_unittest activerecord_unittest2).each do |db|
    if ActiveRecord::Base.connection.execute('SELECT datname FROM pg_database').values.flatten.exclude?(db)
      ActiveRecord::Base.connection.execute("create database #{db}")
    end
  end
rescue PG::ConnectionBad
  sleep 1
  retry
end
